### ISSUE TITLE
Should it be possible to change an employee_id?

### ISSUE THREAD

**Issue by forevermatt** [silinternational/idp-id-broker#21]
As I'm working on the RAML spec for a `PUT /user/{employee_id}` endpoint, I was essentially mimicking the `POST /user` endpoint but making the fields optional. However, I realized that for a `PUT` (i.e. updating an existing user) I don't know whether we should allow changing the `employee_id`. My assumption is that the `employee_id` cannot change, but I don't know if that is an accurate assumption.

**Comment by wcjr** [comment]
I had the same question in one of my test scenarios...we're certainly built to allow it since everything will be keyed off of internal database `id`'s, however the `employee_id` is really forming the glue with external consumers so I'm not sure if we can say "yes" without some careful consideration.  With great fear and trembling, I say we **should** allow the `employee_id` to change.  Presumably if the `employee_id` were to change on an external system it would need to change in the broker as well.  One pertinent question is, "Shall we simply dump the password history in such a case?"  I think it's ok but submit this is at least one issue we need to address clearly.

**Comment by wcjr** [comment]
I just realized a problem with this.  `employee_id`, `username` and `email` must be unique in the `User` table so if the `employee_id` were to change but `username` and/or `email` did not, the API will fail because `username` and/or `email` would already exist.

**Comment by forevermatt** [comment]
I think that would only be a problem if we were creating a new record then deleting the old record. Since the default behavior would simply be to change the value of the `employee_id` on the existing record, I don't think there will be any conflict on `username` or `email` since the record whose `employee_id` is being changed is the only record with that `username` and `email`. Right?

**Comment by wcjr** [comment]
yes, that helps.

**Comment by fillup** [comment]
The intent for using employeeNumber as our key to identify users is that it should never change, whereas their email or username could change. I don't think we need to support changing an employeeNumber via the APIs at this time. I think even with standalone user management we would just generate the employeeNumber to ensure uniqueness and it would not be something the admin would be able to change.

**Comment by forevermatt** [comment]
Closing this since `question` issue now that we've come to a conclusion and added a to-do issue: #24
